' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml participant_identifier_examples

' quoted_display_with_alias
participant "Quoted As Id" as QuotedAsId <<component>>

' alias_with_quoted_display
participant IdAsQuoted as "Id As Quoted" <<component>>

' display_with_alias
participant LeftId as RightId <<component>>

' quoted_display
participant "Quoted Only" <<component>>

' alias_only
participant IdOnly <<component>>

QuotedAsId -> IdAsQuoted : callQuotedAsId()

IdAsQuoted -> RightId : callIdAsQuoted()

RightId -> "Quoted Only" : callIdAsId()

"Quoted Only" -> IdOnly : callQuoted()

IdOnly -> QuotedAsId : callId()

@enduml
